In [6]:
# -*- coding: utf-8 -*-
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
 
word_to_ix = {'hello': 0, 'world': 1}
embeds = nn.Embedding(2, 5)
hello_idx = torch.LongTensor([word_to_ix['hello']])
hello_idx = Variable(hello_idx)
hello_embed = embeds(hello_idx)
print(hello_embed)

tensor([[-0.9823,  1.0616,  0.4901,  0.2739,  0.1203]],
       grad_fn=<EmbeddingBackward>)


In [9]:
hello_idx

tensor([0])

In [8]:
in_embed=nn.Embedding(10, 3)
input = torch.LongTensor([[1,2,4,5],[4,3,2,9]])
in_embed(input)

tensor([[[ 0.1742, -0.5092,  0.1653],
         [ 0.8138,  0.7481, -2.1624],
         [ 0.4389,  0.7282, -0.6032],
         [ 0.2989, -1.1595, -1.2180]],

        [[ 0.4389,  0.7282, -0.6032],
         [-0.4362, -0.5702,  0.9390],
         [ 0.8138,  0.7481, -2.1624],
         [ 1.1843, -0.1688, -0.2293]]], grad_fn=<EmbeddingBackward>)