In [1]:
import numpy

In [2]:
import torch
from torch.autograd import Variable

In [3]:
x=torch.rand(5,3)
x

tensor([[0.8072, 0.5242, 0.4859],
        [0.3812, 0.1046, 0.7571],
        [0.0885, 0.8246, 0.8330],
        [0.0714, 0.7566, 0.2653],
        [0.1111, 0.0959, 0.7797]])

In [4]:
y=torch.ones(5,3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
z=torch.zeros(2,5,3)
z

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [6]:
torch.cuda.is_available()

False

In [7]:
from torch.autograd import Variable

In [8]:
x=Variable(torch.ones(2,2),requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [9]:
y=x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [12]:
z=y*y
t=torch.mean(z)
t

tensor(9., grad_fn=<MeanBackward0>)

In [14]:
z.grad_fn

In [15]:
t.backward()

In [17]:
x.grad

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])